defaults: 
 prefix: " "
 suffix: " "
 urgent: true
 fg: "#aabbcc"
date: 
 prefix: " "
time: 
 prefix: " "
memory: 
 prefix: " ram "
cpu: 
 prefix: " cpu "
disk: 
 prefix: " hdd "
dnf: 
 prefix: " dnf "
pasink: 
 states: 
  muted: 
   prefix: " audio(mute) "
  unmuted: 
   prefix: " audio "
pasource: 
 states: 
  muted: 
   prefix: " mic(mute) "
  unmuted: 
   prefix: " mic "
nic: 
 states: 
  "wireless-up": 
   prefix: " wifi "
  "wireless-down": 
   prefix: " wifi "
  "wired-up": 
   prefix: " lan "
  "wired-down": 
   prefix: " lan "
  "tunnel-up": 
   prefix: " tun "
  "tunnel-down": 
   prefix: " tun "
battery: 
 states: 
  charged: 
   suffix: " full "
  charging: 
   suffix: " chr "
  discharging_critical: 
   prefix: " ! "
   suffix: " dis "
  discharging_low: 
   suffix: " dis "
  discharging_medium: 
   suffix: " dis "
  discharging_high: 
   suffix: " dis "
  discharging_full: 
   suffix: " dis "
